tap 'homebrew/cask'
tap 'homebrew/cask-eid'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/bundle'

brew 'tree'
brew 'go'
brew 'k9s'
brew 'kubectx'
brew 'wget'
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'
brew 'telnet'
brew 'terminal-notifier'

cask 'iterm2'
cask 'docker'
cask 'font-fira-code'
cask 'macdown'
cask 'visual-studio-code'
cask 'firefox'
cask 'karabiner-elements'
cask 'rectangle'
cask 'keepingyouawake'