code --install-extension attilabuti.vscode-mjml
code --install-extension Dart-Code.dart-code
code --install-extension Dart-Code.flutter
code --install-extension foxundermoon.shell-format
code --install-extension gornivv.vscode-flutter-files
code --install-extension James-Yu.latex-workshop
code --install-extension josephtbradley.hive-sql
code --install-extension karyfoundation.comment
code --install-extension mikestead.dotenv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.Go
code --install-extension Nash.awesome-flutter-snippets
code --install-extension PKief.material-icon-theme
code --install-extension redhat.java
code --install-extension redhat.vscode-yaml
code --install-extension sensourceinc.vscode-sql-beautify
code --install-extension sibiraj-s.vscode-scss-formatter
code --install-extension SonarSource.sonarlint-vscode
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscoss.vscode-ansible
code --install-extension wholroyd.jinja
code --install-extension zxh404.vscode-proto3
